### ISSUE TITLE
Mistake in Chapter 35

### ISSUE THREAD

**Issue by Nikk-l** [rzach/forallx-yyc#100]
In chapter 35, on page 295 of the printed version, the symmetric relation is symbolized as:

$$\[\forall x\forall y(R(x,y) \rightarrow R(y,z))\]$$

I think there has been an error in introducing the free variable $z$, as emphasized by the box just above this symbolization, and it was rather meant to be defined as:

$$\[\forall x\forall y(R(x,y) \rightarrow R(y,x))\]$$

This same error also shows itself in the practice exercise B of the same chapter.

**Comment by rzach** [comment]
Good catch, thanks!
