### ISSUE TITLE
Proof rules for negation

### ISSUE THREAD

**Issue by wyleyr** [rzach/forallx-yyc#11]
Via email, I said: 

> Mainly the problem here is that the text calls '\bot Introduction' the rule that I think of as '\neg Elimination'; there is no '\neg Elimination' rule.  This breaks the nice symmetry of having two I/E rules which define each connective.  I also gave students a problem about explaining why we can define '\neg P' as 'P \eif \bot'.  This problem would make more sense if the insight they were expected to get was: the I/E rules for negation just become instances of the rules for the conditional.

Richard Zach said:
> I agree. This shouldn't be too hard to fix: rename all the rules in 
> existing proofs, and rewrite 15.7 and 15.8 (probably also: reverse them)?
>
> (I'm also not sure about using the TND rule as opposed to the classical 
> absurdity rule.)

**Comment by catrincm** [comment]
So your suggestion is to have the current-botI as new-¬E, and have botE and ¬I as they currently are. Then the new system would have no botI rule, and you still need TND as a rule (eg to derive LEM) so that doesn't then fit in. 

A nicer alternative would maybe to keep bot rules as they are and replace TND with 
||¬A (assume)
||bot
|A

(That's then the proof system used in Halbach's logic manual. But a consequence of that change is that proving LEM from it is a massive task! So perhaps that's not so useful, although it's more pleasing on the eye, as it were).

**Comment by rzach** [comment]
That is the solution I favor. It's hat prawitz calls the classical absurdity rule; I propose we call it Indirect proof (IP). TND would become a derived rule. (Tricky to derive, but not so massive! Or, not more massive than DeM).

**Comment by rzach** [comment]
PS: One thing that's holding this up is that I want the proof checker to not break, but I've now gotten it to work and it should not be hard to make those changes.

**Comment by rzach** [comment]
I've drafted the necessary changes. They're in branch https://github.com/rzach/forallx-yyc/tree/issue11

See CH 15, 19 and Appendix B.

[forallxyyc.pdf](https://github.com/rzach/forallx-yyc/files/1346503/forallxyyc.pdf)

**Comment by rzach** [comment]
Aaaand the rules are working in the proof checker https://github.com/OpenLogicProject/fitch-checker/issues/2

**Comment by catrincm** [comment]
Thanks! I'm still working out how to use GitHub properly. One thing, though is that I prefer the name Explosion to ECQ. Mostly because of trying to avoid latin which I think needlessly puts students off.

**Comment by rzach** [comment]
Changed rule names to "less pretentious." Also in proof checker.

PDF of new version: [forallxyyc.pdf](https://github.com/rzach/forallx-yyc/files/1347635/forallxyyc.pdf)

**Comment by wyleyr** [comment]
This is great; thanks for making these changes! One nitpick: now that \bot-Introduction has been renamed to \neg-Elimination, wouldn't it make sense to switch the order of the lines in the citation? That is, as with the other elimination rules, the premise containing the eliminated connective should be cited first.

Would it make sense to start converting proofs in the solutions manual to use the new rules?

**Comment by rzach** [comment]
Ah, good point, yes. So ~E and _|_I are actually different rules then. So I'll have to go through it and change all the \ri's to \ne's which is probably cleaner anyway. (Are we supposed to be sticklers about the order of the justifications? The solution to the second problem of 15.A suggests yes, but I didn't see a statement explicitly anywhere. The proof checker doesn't care.)

If you're volunteering to go through the solutions manual, sure!  I fear we might have to actually move some exercises around -- with TND it was not too big of a deal to prove 15.C.7, but this is in the chapter on basic rules, and it'll be a lot harder with IP -- so probably move that into chapter 16 which needs examples of TND/LEM anyway.  15.C.12 will be easier with IP (just the second subproof), but we'll need a few more examples of IP in use/as exercises. I also added a few exercises already. Must keep track somewhere so we can make a list of what's changed for the next edition.
