### ISSUE TITLE
Conversion to HTML

### ISSUE THREAD

**Issue by rzach** [rzach/forallx-yyc#23]
Figure out a good way to convert everything to HTML and ePub.

**Comment by david-a-wheeler** [comment]
There are many options, but I don't know if any are good. The [TeX FAQ has a list of ways to generate HTML](https://texfaq.org/FAQ-LaTeX2HTML). There's also [pandoc](https://pandoc.org/)/

**Comment by rzach** [comment]
Back when I opened this, the most promising option seemed to be latexml. The main problem is that the code uses *a lot* of configurations, custom TeX code, and packages (esp cleveref, subfiles). The customizations use xparse, which still isn't supported, although some of the others now are.

**Comment by rzach** [comment]
LaTeXML .8.7 now does a decent job. The result is here: https://forallx.openlogicproject.org/html/index.html

I took some hints from these people (@0-andy-0 ?)
https://hackmd.io/@UoL-IWG/latexml

**Comment by 0-andy-0** [comment]
Glad to be of help. Nice navigation button :-)
Andy
(also ***@***.***)

**Comment by rzach** [comment]
Thanks to @brucemiller and @dginev (https://github.com/brucemiller/LaTeXML) and @xworld21 / @vlmantova (https://github.com/vlmantova/bookml) this is now done!
