### ISSUE TITLE
Error in citation convention for negation elimination

### ISSUE THREAD

**Issue by jenniferrcarr** [rzach/forallx-yyc#24]
In the explanation of negation elimination, the current version says: "we always cite the sentence first, followed by its negation" (116). But where the rule is presented immediately above this, the negation of the sentence is cited first, followed by the sentence. 

(Thanks for the fantastic resource!)

**Comment by catrincm** [comment]
I think we don't care which order they're cited in (e.g. for biconditional rule there's no additional specification of citation order) so we should remove that sentence Jennifer highlights.

**Comment by rzach** [comment]
Done. The other E rules do in fact specify the order. Of course you're free to not enforce that but some people may want it. I've left it in but fixed it. Thanks for reporting it!

**Comment by rzach** [comment]
Say hi to Clinton and and Kerry for me.
