### ISSUE TITLE
I cannot build the book

### ISSUE THREAD

**Issue by vedgar** [rzach/forallx-yyc#32]
The instructions say to clone the repo and LaTeX the book. But no matter which command I use to LaTeX it, I get no further than
    ! Undefined control sequence.
    l.4 \Language
         {en-US}

How exactly do I build the book?

**Comment by rzach** [comment]
I'm guessing you don't have pdfx.sty installed. Can you attach your log?

**Comment by vedgar** [comment]
I don't think installation instructions mention any pdfx.sty. 
Here is my .log file.
[forallxyyc.log](https://github.com/rzach/forallx-yyc/files/3587788/forallxyyc.log)

**Comment by rzach** [comment]
It's part of TeXlive, but you have an old version. Update your TeX distribution, or download the current version of pdfx https://ctan.org/pkg/pdfx?lang=en

**Comment by vedgar** [comment]
Ok, thank you. Now I'm stuck on

! Class memoir Error: \footskip (27.46295pt) is too large for \lowermargin (6.9
9733pt) by 20.46562pt.

See the memoir class documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.31 

Yes, I've seen the documentation. It just says to decrease footskip or increase lowermargin, but I don't know what their values should be.

**Comment by rzach** [comment]
Log please!

**Comment by vedgar** [comment]
Sorry. :-) Here it is.
https://gist.github.com/vedgar/b699eda3b28842700d46eb8ff2851606
(It seems too big to paste here.)

**Comment by rzach** [comment]
Hm, I'm at a loss. It compiles without error for me on the same version of memoir that you're using. Those dimensions are set automatically. Did you change the source file in any way?

**Comment by vedgar** [comment]
No, but I think I know what's the problem. I used _too new_ pdflatex this time. There is a developer preview of the format that will be released on October 1st (https://www.latex-project.org/news/2019/09/01/LaTeX-dev-format/ for more info), and it gives an error, while the regular one (from December of last year) doesn't. I still think you should fix that, of course, since in few weeks it will become default (or report it to LaTeX project, if you think they've done something wrong).

Also, at https://www.diffchecker.com/5IdZJmTB is the diff of both logs (expires in 23 hours). I think the main difference is the font scaling: look at the line 1911|1917. Dev LaTeX rescales `T1/Baskervaldx-TLF/m/n' to 10.95pt, while current one rescales it to 10.0pt. My intuition is that the bigger fontsize makes less text be able to fit on the page, causing the discrepancy.

**Comment by rzach** [comment]
After I upgraded to Ubuntu 20.04 I ran into the same problem. I couldn't really figure out what went wrong, but my guess is that \setlxvchars did not work and properly before and somehow on old TeXLive it set the width of the typeblock to 300pt regardless of what the actual font was. That made the textblock to high in most cases. So I have now just hardcoded the width to 300pt in commit dc05ecd1c67be8dc0382153c03f1b236a9cc926a 
If you haven't given up can you check if that fixes it for you?

**Comment by rzach** [comment]
I'll close this unless you still have this problem

**Comment by vedgar** [comment]
Yes, that problem seems solved. There are about 30 over/undefull hboxes, so there are probably more problems, but at least the PDF gets made.

**Comment by rzach** [comment]
Great, thanks!
