### ISSUE TITLE
Typo (missing quotation sign)

### ISSUE THREAD

**Issue by emilberwald** [rzach/forallx-yyc#38]
A missing qoutation sign at the very end ('B')
https://github.com/rzach/forallx-yyc/blob/d5822335642685cb4be39bf7ba1829d1dc70c0a7/forallx-yyc-tfl.tex#L838

I hope you don't mind me reporting these minor typos! I think it is an interesting thing to have a book on github.

**Comment by rzach** [comment]
Not at all please keep it up!
