### ISSUE TITLE
Chapter 22 could be better structured

### ISSUE THREAD

**Issue by graforlock** [rzach/forallx-yyc#39]
In the chapter you first introduce scoped quantifiers in such style: 

`∃x(Fx ∧ Dx)`

Yet discuss scope at the very end of the chapter, which is a bit confusing. If anything, it would make more sense to do this the other way around.

**Comment by rzach** [comment]
I've moved the syntax section up a bit to before we use "scope" in the text. It's not perfect but I think there's value in leaving the pedantic discussion of syntax to after students have developed a feel for FOL.
