### ISSUE TITLE
Possible typo in exercise of chapter 17

### ISSUE THREAD

**Issue by jesuslop** [rzach/forallx-yyc#43]
On ch. 17, "constructing proofs", pg. 130, practice exercises, in C.5 i think there is a typo,

(A or ~B) -> (A -> B) is not a tautology (check for instance [here](https://web.stanford.edu/class/cs103/tools/truth-table-tool/)). It would have been, for instance, if the outermost consequent were reversed, to B -> A, having

(A or ~B) -> (B -> A) 

version 2cf987e (2020-08-07)

btw, thanks for all this effort.

**Comment by rzach** [comment]
Right you are! Thanks.
