### ISSUE TITLE
Parallelism errors in 2.3 Formal validity examples

### ISSUE THREAD

**Issue by chreliot** [rzach/forallx-yyc#58]
All six examples in 2.3 have this issue:

> Either Mei is a mathematician or a botanist.

gives us as disjunctive alternatives a sentence and a noun, which have different grammatical functions.

per _Chicago Manual of Style_ 5.244, for example:

> Correlative conjunctions such as either–or, neither–nor, both–and, and not only–but also and some adverb pairs such as where–there, as–so, and if–then must join grammatically parallel sentence elements. It is a common error to mismatch elements framed by correlatives.

This can be fixed with the pattern

> Either Mei is a mathematician or Mei is a botanist.

or the pattern 

> Mei is either a mathematician or a botanist.

Would you be receptive to a pull request for all the examples with one of these patterns?

**Comment by rzach** [comment]
Good catch; yes please. I think I might prefer the second pattern.

**Comment by rzach** [comment]
Fixed by commit 1269730
