### ISSUE TITLE
Is sending a pull request the only means of providing corrections/feedback?

### ISSUE THREAD

**Issue by kedarmhaswade** [rzach/forallx-yyc#65]
First off, thank you for making this available on GH. It just helps!

I couldn't find an instruction in the book preface or the GH repo about how to submit errata. Can that be clarified somewhere (preferably the preface)? If sending a PR is the way to go, please clarify it here and close the issue. I will send a PR.

**Comment by rzach** [comment]
PR is preferred but you can also file an issue with the requested change.

**Comment by kedarmhaswade** [comment]
If it is PR, I believe a separate PR is needed for every _atomic_ change, right? I can send a PR. 

But for something that is likely to be more contentious, perhaps an issue is better because then we can have a discussion, reach a consensus, and then a PR can be sent.
