### ISSUE TITLE
In appendix A, add | as alternative for disjunction ("or")

### ISSUE THREAD

**Issue by david-a-wheeler** [rzach/forallx-yyc#68]
Please modify Appendix A to add "|"
as an alternative symbol for disjunction ("or"), both in the discussion about "or" and in
the following summary table.

This is used. For example, prover9 uses "|" for "or", "&amp;" for "and", and so on,
as documented here:
https://www.cs.unm.edu/~mccune/prover9/manual/2009-11A/syntax.html

Thanks so much!

**Comment by rzach** [comment]
Fixed in 33bdea908cbc772a1f18d2814c1200b8cb44cf4b, thanks!
