### ISSUE TITLE
A doubt about 12.5 example 2

### ISSUE THREAD

**Issue by yhirshhorn** [rzach/forallx-yyc#72]
In 12.5 example 2 the book provides "Jan is neither bold, nor not-bold" as a limit to validity tests using TFL.

The problem described is that a possible symbolization would be: $'\neg J \wedge \neg \neg J'$ which is a contradiction.
It is explained that we could have added "Jan is on the borderline of boldness" and that is why the original sentence is possible.

Does this not mean that our symbolization was faulty to begin with? True, "Jan is bold" would probably be symbolized as some sentence letter, say 'J', but since in reality the phrase "not-bold" is not the complement of "bold", is it not a mistake to symbolize it as $'\neg J'$ to begin with? Shouldn't we have added at least one more sentence letter for "not-bold", say 'N', and get the following symbolization: $'\neg J \wedge \neg N'$ which is not a contradiction?

Now, if this example comes to show that misuse of TFL can bring us faulty test results, it is, of course, true, but it is not a limit of TFL specifically but of any possible logic language, existing or hypothetical. Wouldn't it be clearer to mention that this is a limitation that is not unique to TFL?

**Comment by kedarmhaswade** [comment]
I believe you mean "bald", and not "bold".

I believe what the text is trying to say is that even though in TFL we adhere to the _Law of Excluded Middle_, in English that may not always be the case. Trying to _TFL-symbolize_ such English sentences may have unacceptable results. Such adamant _TFL-symbolization_ is what the text is trying to discourage. We have just got to accept that TFL has its limitations. Those limitations are likely to remain even if you symbolize some English sentences differently.

A similar example appears in 5.1 where Jane is in a state of blank indifference.

**Comment by kedarmhaswade** [comment]
The symbolization above has _formal_ issues. Following is more formal. Here is the key:
𝒥: Jan is bald.
𝒩: Jan is **not-bald**.

Then, at the risk of being adamantly TF-logical, we can unambiguously symbolize the English sentence "Jan is neither bald nor not-bald", as

¬𝒥 ∧ ¬𝒩

in TFL.

I believe, however, that we are already down a slippery slope. But I agree, we can provide a clarification. I am not so sure that the example is a misuse of TFL symbolization.

**Comment by yhirshhorn** [comment]
I am not sure I understand now.

1. What is the slippery slope we are in?

2. What is the difference between 5.1 and 12.5? I wanted to infer from their similarity that if $\neg H$ is a mistake there, then $\neg \scriptN$ is a mistake here. Why don't you agree?

**Comment by kedarmhaswade** [comment]
I am saying we could have symbolized this in any way we want. I am not convinced that the ambiguity goes away because of that. That said, yes, there is a room for improvement in the example. Please consider submitting a pull request!

**Comment by yhirshhorn** [comment]
I can't submit a PR if I don't understand the problem you are pointing at.

1. What is the slippery slope?

2. Why can we symbolize it any way we want here, but not in 5.1?

**Comment by rzach** [comment]
I hope the expanded explanation addresses your concern. It's an important point but you can't really do it justice without going into a whole discussion of vagueness and alternative logics
