### ISSUE TITLE
Discuss: Is the rule #7 needed in the definition of TFL sentence?

### ISSUE THREAD

**Issue by kedarmhaswade** [rzach/forallx-yyc#73]
In §6.2, we formally define TFL sentence.

In the given inductive definition that constructs a TFL sentence, is "Nothing else is a sentence." needed? I doubt if it provides any _constructive_ value. It is okay to use it for emphasis, but then it can be a part of exposition, not the definition.

**Comment by rzach** [comment]
It is a standard part of inductive definitions singling out the set of TFL sentences as the smallest set satisfying the other clauses.
