### ISSUE TITLE
Make a passing reference to a hypothetical postfix notation as an alternative to bracketing?

### ISSUE THREAD

**Issue by kedarmhaswade** [rzach/forallx-yyc#75]
I haven't researched the literature to establish if [postfix notation](https://en.wikipedia.org/wiki/Reverse_Polish_notation) has been tried on TFL sentences. I have written about it [here](https://docs.google.com/document/d/150fdbWwLgrSsegM7sUZgB0L-VsQii8mZ0DHWuWUNXZM/edit#heading=h.oxzzd8a3vy55). 

Summarily:

> Compare, for instance, 𝒜ℬ𝒞∧∨ with 𝒜∨(ℬ∧𝒞). We can prove that the postfix notation can create unambiguous TFL Sentences (see below), but whether they will be readable is difficult to determine; it may also be subjective. Sometimes, however, I fancy thinking that postfix notation may serve the TFL Sentences well, once you get used to it.

Is it a good idea to make a passing reference to such a notation in TFL (§ 6.3)?

**Comment by rzach** [comment]
I think it would be bit tangential and possibly confusing in the main text. It is mentioned at the end of appendix A ("Polish notation")

**Comment by kedarmhaswade** [comment]
Wow! Thank you for drawing my attention to the appendix A. I had missed that. OTOH, it feels good that I had that thought without referring to the appendix :-). 

I respect your decision to not even mention appendix A in the main text (section 6.3), but I don't think it is _tangential_. It is very much related to the need of bracketing to disambiguate a sentence. Another benefit of such a reference would be to avoid the creation of an issue like this one!
