### ISSUE TITLE
Spell checks

### ISSUE THREAD

**Issue by davidvandebunte** [rzach/forallx-yyc#81]
Spell check "contradition" in [Chp 17](https://forallx.openlogicproject.org/html/Ch17.html).

Spell check "subroof" in [Chp 18](https://forallx.openlogicproject.org/html/Ch18.html#S4).

Spell check "apropriate" in [Chp 42](https://forallx.openlogicproject.org/html/Ch42.html).

In [Chp 43](https://forallx.openlogicproject.org/html/Ch43.html) the following sentence has an unmatched bracket, besides being otherwise hard to read:

> In fact, we could have added rule R5 to T alone, and leave out rule R5)

In [Chp 30](https://forallx.openlogicproject.org/html/Ch30.html), replace "just in case" with "if":

> and stipulate that ‘R(x,y)’ is to hold of x and y just in case there is an arrow running from x to y in our diagram.

**Comment by rzach** [comment]
Thanks!
