### ISSUE TITLE
HTML version: website titles

### ISSUE THREAD

**Issue by davidvandebunte** [rzach/forallx-yyc#82]
The website title associated with every HTML page (used in e.g. auto-generated bookmarks and the presentation of the website in search engines) seems to have been auto-generated in an incorrect or at least non-ideal way. For example: [Chapter 12 Semantic concepts ‣ Part III Truth tables ‣ forall x: Calgary. An Introduction to Formal Logic‣ Part III Truth tables ‣ forall x: Calgary. An Introduction to Formal Logic](https://forallx.openlogicproject.org/html/Ch12.html#S6).

**Comment by rzach** [comment]
That's a LaTeXML issue, and should be fixed in the next release: https://github.com/brucemiller/LaTeXML/issues/2162
