### ISSUE TITLE
A few more spell checks ✓

### ISSUE THREAD

**Issue by davidvandebunte** [rzach/forallx-yyc#89]
In [25.3](https://forallx.openlogicproject.org/bookml/Ch25.html#S3), replace capital F with lowercase f in the pointwise continuous and uniformly continuous definitions.

In [31.1](https://forallx.openlogicproject.org/bookml/Ch31.html#S3), spell check susbstitution.

In [Chp 36](https://forallx.openlogicproject.org/bookml/Ch36.html), the language "provided provided" is used twice. It looks like this is a typo that got copy-pasted?

**Comment by rzach** [comment]
Thanks for this!
