### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by goo-design** [rzach/forallx-yyc#92]
p.13 “valid if it is formally valid” for “valid iff it is formally valid”

**Comment by rzach** [comment]
It already says "if" I think?

**Comment by goo-design** [comment]
Sorry I meant the opposite. “iff” instead of “if”, or maybe “only if” instead of “if.”

**Comment by rzach** [comment]
fixed in https://github.com/rzach/forallx-yyc/commit/034ff3de5f79708339a389beb32bd8cd1604052b; thanks!
