### ISSUE TITLE
Truth table typo

### ISSUE THREAD

**Issue by insighthorizon** [rzach/forallx-yyc#95]
In solutions for chapter 15, exercise A. 2.:
- The second row should have the opposite truth value.
![image](https://github.com/rzach/forallx-yyc/assets/25298569/a664f921-c1d4-4202-a4fd-98dc597fb2e1)

**Comment by rzach** [comment]
fixed in https://github.com/rzach/forallx-yyc/commit/034ff3de5f79708339a389beb32bd8cd1604052b; thanks!
