### ISSUE TITLE
Probably a typo

### ISSUE THREAD

**Issue by insighthorizon** [rzach/forallx-yyc#96]
On the page 130 (Chapter 17.5), instead of

"The subproof started on line 3 is still open at line 3."

there should be the sentence

"The subproof started on line 3 is still open at line 5."

(The sub-subproof is still open at line 5, which is the problem being refered to in that paragraph.)

**Comment by rzach** [comment]
fixed in https://github.com/rzach/forallx-yyc/commit/034ff3de5f79708339a389beb32bd8cd1604052b; thanks!
