### ISSUE TITLE
Mistake in 25.2

### ISSUE THREAD

**Issue by Nikk-l** [rzach/forallx-yyc#98]
In section 25.2, on page 217 of the printed version, it is defined that:

i: Imre
k: Karl
L(x,y): __x loves __y
M(x,y): __y loves __x

However, on the following page (p.218), the sentence 'M(i,k)' is rather deconstructed into the sentence 'Imre loves Karl', when that should rather be the sentence for 'M(k,i)'. This error is emphasized in the following paragraph, which seems to have corrected this issue.

**Comment by rzach** [comment]
Thanks!
